### ISSUE TITLE
Training New Weights?

### ISSUE THREAD

**Issue by Max-Fu** [willard-yuan/flask-keras-cnn-image-retrieval#14]
Currently, imagenet weights are used. Is it possible to train the weights based on the indexing images? (using techniques such as unsupervised learning)

**Comment by willard-yuan** [comment]
@Max-Fu To improve the performance of Instance Retrieval (Instance Search, or Object Retrieval), especially in vertical industry such as clothes retrieval, Training a new model is essential. You can try triplet network or siamese network. You can use local feature such as SIFT to generate the pairwise samples. For unsupervised learning, you can try the methods in [**cnn-cbir-benchmark**](https://github.com/willard-yuan/cnn-cbir-benchmark). But these methods are not promising.

**Comment by willard-yuan** [comment]
If there is no question, I closed the issue. You are welcome to reopen it if you have questions.

**Comment by dgtlmoon** [comment]
@willard-yuan so essentially you're saying you can use SIFT (or others like ORB) to build a list of pairwise samples? but SIFT is not always perfect (rotation invariance etc).. and then you are feeding not-perfect data into your network... so hmm.. I'm unsure too

**Comment by dgtlmoon** [comment]
to clarify, using SIFT or ORB to generate descriptors and use those descriptors to build a pair listing of matching images
