### ISSUE TITLE
How to get the scores of images?

### ISSUE THREAD

**Issue by BLACKmaba** [willard-yuan/flask-keras-cnn-image-retrieval#15]
why do this? thank you for your answer.
`scores = np.dot(norm_feat, feats.T)
rank_ID = np.argsort(scores)[::-1]
rank_score = scores[rank_ID]`

**Comment by willard-yuan** [comment]
The similarity is measured by cosine similarity. The above lines compute the cosine similarity, then sort the scores.

**Comment by willard-yuan** [comment]
@snapfinger You are welcome to reopen the issue if you have question.
