### ISSUE TITLE
后续有考虑优化吗？

### ISSUE THREAD

**Issue by zecynx** [willard-yuan/flask-keras-cnn-image-retrieval#18]
感谢整理分享的论文！
看了下您的实现，用VGG16提取特征，把两张图片的点积作为相似分数，后续有考虑优化吗？

**Comment by willard-yuan** [comment]
特征优化需要结合特定的数据以及任务来做，使得优化的模型不具备普适性。您指的后续优化，希望是哪些方面？

**Comment by zecynx** [comment]
因为现在的实现是将全部特征都丢到内存里，对于数据量大肯定是不适用的。
比如：
- 用些“层级搜索”的手段来实现粗、细不同颗粒度的匹配，然后再计算相似分数
- 简化模型，将数据压缩到更低的纬度

**Comment by willard-yuan** [comment]
@Jjjeaswn 索引这块优化有很多方法，我在我的[博客](http://yongyuan.name/blog/)里面介绍过非常多的优化方法。至于为什么没在这个里面做优化，主要出于两点考虑：

- 实际在应用的时候，索引包括抽取特征的服务，在数据量非常大的时候，实现一般采用的都是C++，C++一旦包含进来，会使得整个项目不再简洁，有的同学看到就望而生畏，并且图像视频检索，通常需要根据自己特性的任务去做优化，很难提供一个通用型的框架；
- 尽量避免依赖，保持整个项目简洁易懂。通常其实只要理解了原理，很多优化等都可以自己做了，并且索引这块，有很多第三方工具包，网上介绍的资料已经沟通，再做这样一个工作，只是堆砌，没有太大意义

另外，索引这一块，其实除了用faiss开源的解决方案，也有一套不依赖任何第三方的实现[opq](https://github.com/willard-yuan/cvtk/tree/master/opq)，其实是非常好的，再结合上HNSW，可以把整个索引做成HNSW+OPQ的方式，可以支持千亿图片的索引。

**Comment by willard-yuan** [comment]
如果没其他的问题，我先把issue先关了，有问题你再打开。
