### ISSUE TITLE
请问如何对检索的结果进行评测呢？

### ISSUE THREAD

**Issue by ruizewang** [willard-yuan/flask-keras-cnn-image-retrieval#22]

**Comment by world2025** [comment]
@22881916 请问那个index.py文件如何修改呢，我改了之后还是说index.py: error: the following arguments are required: -database, -index，谢谢

**Comment by willard-yuan** [comment]
评价指标可以采用mAP，具体mAP的含义，可以参考这个[信息检索评价指标](http://yongyuan.name/blog/evaluation-of-information-retrieval.html)。

**Comment by willard-yuan** [comment]
如果没有问题，我先关了，有问题可以再重新打开。

**Comment by ruizewang** [comment]
好的，谢谢您的帮助
