### ISSUE TITLE
相似度计算 以及预训练模型问题

### ISSUE THREAD

**Issue by yyjabidintg** [willard-yuan/flask-keras-cnn-image-retrieval#24]
有两个问题想请教下:
1.除了余弦相似度以外还有啥比较推荐的相似度计算方式吗
2. 预训练模型是在imagenet上训练的 它的特征为何可以用它其他新的数据集上 作为特征提取??

谢谢

**Comment by willard-yuan** [comment]
@yyjabidintg 1. 除了算余弦相似度外，还可以用欧式距离，实际应用的时候，可以先对特征做L2归一化，归一化后，余弦相似度和欧式距离是等价的。余弦相似度的好处是，算出来的相似度距离范围在[-1, 1]之间，便于分析特征和设置阈值。

2. 这个问题的答案详见 #23 。

**Comment by YixuanZhang99** [comment]
您好！您的代码中在计算相似度的时候是用的余弦相似度吗？为什么没有除以它们的向量的二范数的乘积呢？

**Comment by willard-yuan** [comment]
@lazybart 用的是余弦相似性，因为在提特征的时候，已经做了L2归一化，所以不需要除以L2范数了。

**Comment by willard-yuan** [comment]
先关闭了，有问题在可以开启issue。
