### ISSUE TITLE
Is relying on top weights always what the user should expect?

### ISSUE THREAD

**Issue by dgtlmoon** [willard-yuan/flask-keras-cnn-image-retrieval#29]
Sort of mentioned in #14 , but more specifically I think the problem is that `model.extract_feat(img_path)
` in `index.py` is always looking at the top/last layer which is the most 'abstract' in VGG16, so if the network can get a good confidence score on something like seeing a dog in the image, then other images will always be 'similar'.

(Because we are using the existing trained weights)

I'm not totally sure what todo , but feels to me like the network should pull features from a middle layer, so that it's comparing edges, lines, and other low level objects instead of high level abstract information? thoughts?

for example

- If I have a lot of photos of paintings, but I want to search for very similar paintings.. the photos with the border/frame around the painting will always be more 'similar' regardless of the contents of the painting

**Comment by willard-yuan** [comment]
@dgtlmoon Sorry for later reply. What you think is absolutely right. For instance retrieval or object retrieval, Middle layer is a good choice.There are many papers refer to instance retrieval. You can refer to the [awesome-cbir-papers](https://github.com/willard-yuan/awesome-cbir-papers) to get more ideas to do instance retrieval. The project is a simple tutorial for study.

If you have question, feel free to reopen the issue.
