### ISSUE TITLE
特征提取加速问题

### ISSUE THREAD

**Issue by adu-web3** [willard-yuan/flask-keras-cnn-image-retrieval#32]
有上万张图片需要提取特征，请问有没有能够加速提取速度的tips？

**Comment by willard-yuan** [comment]
可以使用多进程的方式，具体可以参考这个例子[oxford5k_feats_extract.py](https://github.com/willard-yuan/cnn-cbir-benchmark/blob/master/fc_retrieval/src/oxford5k_feats_extract.py).
