### ISSUE TITLE
和triplet loss计算的差异

### ISSUE THREAD

**Issue by xu1718191411** [willard-yuan/flask-keras-cnn-image-retrieval#33]
你好
我正在尝试你的作品。
请教一个问题，请问该方法总结来说是以下方法吗？
用vgg16模型提取query image的特征，再依次做相似度计算，取出相似度最高的图片。
请问以上方法适用于「相似服装」的查找吗。

市面上相似服装的查找的方法最近有triplet loss的方法。请问triplet loss方法和本方法都有哪些差异呢。
谢谢

**Comment by Deepakpajero** [comment]
I don't know your language
