### ISSUE TITLE
如何使用resnet？

### ISSUE THREAD

**Issue by volunteers** [willard-yuan/flask-keras-cnn-image-retrieval#34]
你使用的keras的vgg16相对比较慢， 如果要换成keras的resnet， code哪些部分要改变？谢谢

**Comment by willard-yuan** [comment]
@volunteers 你需要修改下[extract_cnn_vgg16_keras.py](https://github.com/willard-yuan/flask-keras-cnn-image-retrieval/blob/master/extract_cnn_vgg16_keras.py)，把里面的vgg16模型改成resnet。
