### ISSUE TITLE
请问使用keras 怎么使用rmac或crow pooling 取代max pooling

### ISSUE THREAD

**Issue by KinaZhen** [willard-yuan/flask-keras-cnn-image-retrieval#38]
看了您的博客 http://yongyuan.name/blog/layer-selection-and-finetune-for-cbir.html?nsukey=N9oNq4fRSP%2FTBBMuA%2FGA9hb3dPzeOLNkGKvoYUUMRnPtwQbQjRqPm70SyQcuhTtLZSI5jBFsmeDLohW7s5rd%2FeZXGF4e0TbMwCEqh7VxxeGRKkgbhyJOHIj0yaynoglNQ4Y%2BV2ifXmF41tp%2FECVmERWqM%2BU55apP6mGdUc%2FQpAt5HB%2FxE5uwKI1MnYhzhsl3huTMx5Wk%2FB5dJz8RsdEcGA%3D%3D  提到了rmac 和 crow pooling，如何使用在该项目里呢

**Comment by willard-yuan** [comment]
@KinaZhen 时间太久了，才看到。rmac的代码，可以看这里https://github.com/willard-yuan/cnn-cbir-benchmark，比较容易，自己改一下。
