### ISSUE TITLE
How to load model from local file

### ISSUE THREAD

**Issue by wyfSunflower** [willard-yuan/flask-keras-cnn-image-retrieval#41]
When execute index.py, it will download model file from https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5, but the download speed is very slow and always failed.
then I download the model file from browser. But it can not load model from my downloaded file.
How to load model from my local file? Thanks!

**Comment by willard-yuan** [comment]
@wyfSunflower You can download the model by the link: https://blog.csdn.net/qq_35436571/article/details/97760098.
