### ISSUE TITLE
标题上有写flask，是作者还没完成吗～

### ISSUE THREAD

**Issue by duchengyao** [willard-yuan/flask-keras-cnn-image-retrieval#5]
没有在代码里面找到关于flask的部分，是还没有添加进来吗，谢谢啦～

**Comment by willard-yuan** [comment]
@duchengyao flask的部分还没写，逃~

**Comment by duchengyao** [comment]
原谅你一次好了～

**Comment by duchengyao** [comment]
对了，有个问题，是不是训练图片多了会内存溢出呀，昨天刚试了一下您的代码，跑到200张图片的时候溢出了，还没仔细调试

**Comment by willard-yuan** [comment]
是有可能的，特征提取的时候，会把所有的特征提完后放在一个大的数组里面。不过你这个才200张图片，你内存不至于这么小。

**Comment by duchengyao** [comment]
不是的，内存溢出的原因是重复定义了很多model，而并未被释放，在[另一个issue](https://github.com/willard-yuan/flask-keras-cnn-image-retrieval/issues/4)里面

**Comment by duchengyao** [comment]
我把您的代码改成了resnet-50(+fine tune) + faiss 效果特别快
我们公司也在做图像检索/视频打标签之类的工作，请问您有意向换工作吗？

**Comment by duchengyao** [comment]
我的博客和联系方式在 http://s1nh.org/about
您就是我们需要的人才，请务必联系我，谢谢啦

**Comment by willard-yuan** [comment]
@duchengyao 贵司就是海康威视吗~

**Comment by duchengyao** [comment]
其实不是啦
我们是“衣二三”，C轮5000万美元融资以后想做一些推荐算法来优化我们的客户端。
其中包括用户晒图的衣服，通过打标签来直接对应商品     这类的的工作，对您来说应该是信手拈来的
如果感兴趣的话，我就让我们的hr联系您～

**Comment by willard-yuan** [comment]
@duchengyao flask部分已经完成了，我周末有时间整理了上传上来。演示地址在readme里面。

**Comment by duchengyao** [comment]
太感谢啦^_^
