### ISSUE TITLE
咨询一个大数据量的问题

### ISSUE THREAD

**Issue by keithbyr** [willard-yuan/flask-keras-cnn-image-retrieval#8]
作者你好，从你的方法当中学到很多。 现在有一个问题想请教一下。 在海量数据的情况下，h5py的读取速度和保存速度会变得越来越慢。 我自己做实验的情况来看，刚开始数据从提取特征到最后查找相似度结束大概用时10ms左右。5w张图片以后， 单h5文件的读取和矩阵计算已经占到200ms以上了。 你这边有没有什么好的经验，如何在海量数据下保证图片处理过程的实时性呢?

**Comment by willard-yuan** [comment]
如果只是做实验的话，可以使用二进制流来提升读写速度。如果要在实际中使用的话，特征可以存到hbase里面，至于查询相应速度问题，可以对特征建索引，比如PQ、OPQ等。

**Comment by willard-yuan** [comment]
@keithbyr 我先关了这个issue，如果有什么问题的话，你再打开。
