### ISSUE TITLE
请问有相关论文吗？

### ISSUE THREAD

**Issue by ligaoyi101** [willard-yuan/flask-keras-cnn-image-retrieval#9]
您好，感谢您的分享！ 因为我还是个图像检索方面的小白，所以想系统地学习一下，请问这个项目您是根据哪篇论文做出来的吗？ 或者是什么其他的理论资料呢？ 谢谢了！！期待您的回复

**Comment by willard-yuan** [comment]
抱歉，才注意到。这个检索的过程就是对pool5做最大池化得到512维的特征，这种方式很常见，就好像1+1=2一样，已经是一个共识。你可以参考这篇博文[layer选择与fine-tuning性能提升验证](http://yongyuan.name/blog/layer-selection-and-finetune-for-cbir.html)。
